server:
  port: 8082

spring:
  application:
    name: dubbo-consumer

dubbo:
  registry:
    id: zk-registry
    address: 127.0.0.1:2181
    protocol: zookeeper
    client: curator
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout: 3000
  application:
    qos-port: 33333
