server:
  port: 8081

spring:
  application:
    name: dubbo-provider

dubbo:
  scan:
    base-packages: com.github.mgzu.provider.service
  protocol:
    name: dubbo
    port: 20880
  registry:
    id: zk-registry
    address: zookeeper://127.0.0.1:2181
    protocol: zookeeper
    client: curator
  config-center:
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181
